---
title: "Camerlin, Nathan HW07"
author: "Nathan Camerlin"
date: "2022-11-11"
output: html_document
---
```{r}
rm(list = ls(all.names = TRUE))
gc()

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, caret, mlbench, naivebayes, glmnet, ranger, kernlab, caTools, randomForest, rstanarm, class, knitr, ggplot2)

knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi = 500)
```
# Part A)
# Loading example dataset of choice (Boston Housing).

```{r}
library("MASS")
data(Boston)
```

# Part B)
# Setting the UI

```{r}
library(shiny)
ui <- fluidPage(

  # App title ----
  titlePanel("Boston Housing Data - 1970 Census"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(
      helpText(HTML("<b>Select variables to include in the scatterplot using
      the dropdown menus below.</b><br><br>
                <b><u>Legend:</b></u><br>
                crim: <i>Per capita crime rate</i><br>
                indus: <i>Proportion of non-business acres</i><br>
                chas: <i>Charles River dummy</i><br>
                nox: <i>Nitric oxides concentration
                (parts per 10 million)</i><br>
                rm: <i>Average rooms per dwelling</i><br>
                age: <i>Proportion of owner-occupied units built prior
                to 1940</i><br>
                rad: <i>Index of accessibility to radial highways</i><br>
                tax: <i>Property tax per $10,000</i><br>
                ptratio: <i>Pupil-teacher ratio</i><br><br>")),
      
      # Input: Select data to plot ----
      selectInput("x",
                  "X Variable:",
                  choices = list("crim",
                                 "indus",
                                 "chas",
                                 "nox",
                                 "rm",
                                 "age",
                                 "rad",
                                 "tax",
                                 "ptratio"),
                  selected = "tax", multiple=FALSE),
      
      selectInput("y",
                  "Y Variable:",
                  choices = list("crim",
                                 "indus",
                                 "chas",
                                 "nox",
                                 "rm",
                                 "age",
                                 "rad",
                                 "tax",
                                 "ptratio"),
                  selected = "crim", multiple=FALSE),
      
      selectInput("z",
                  "Color:",
                  choices = list("red",
                                 "blue",
                                 "black",
                                 "green"),
                  selected = "red", multiple=FALSE),
      
    ),
    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Scatterplot ----
      plotOutput(outputId = "scatterPlot")
    )
  )
)

# Setting the server
server <- function(input, output) {
    output$scatterPlot <- renderPlot({
        p = ggplot(data = Boston) +
            aes_string(x = input$x, y = input$y) +
            geom_point(color = input$z, shape = 19, size = 3.5)
        plot(p)
        observeEvent(input$update, print(as.numeric(input$update)))
    })
}

# Setting the Shiny app

shinyApp(ui = ui, server = server)
```
